### PR TITLE
Implement equals() and hashCode() methods

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by Rave-Tian** [comment]
witch class should implement those two methods? can you show me more details,please.

**Comment by CrabeMan** [comment]
Hi, 
Try to add a `SwipeRefreshLayout` around your `RecyclerView` and call `notifyDataSetChanged`, you will see the strange blinking behavior i'm talking about.

I saw on a Glide issue, we need to implement the `equals()` and `hashCode()` for every transformation. I was inspired by [`CircleCrop`](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/resource/bitmap/CircleCrop.java) and [`RoundedCorners`](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/resource/bitmap/RoundedCorners.java).

As [`here`](https://github.com/bumptech/glide/blob/master/library/src/main/java/com/bumptech/glide/load/resource/bitmap/CircleCrop.java#L19), I probably need to set the id to final to prevent the String generation from the class on every `hashCode()` and `updateDiskCacheKey()` methods. I will make a commit


CrabeMan

**Comment by CrabeMan** [comment]
Hi @wasabeef,
When you have a moment, can you please have a look at this pull request.

Thanks

**Comment by wasabeef** [comment]
@CrabeMan Thanks.

**Comment by wasabeef** [comment]
I'm gonna release the changes by this weekend.

**Pull request merged**
