### PR TITLE
Optimize MaskTransformation

### PR DESCRIPTION
**Pull request by start141**
1. Not to create the mask bitmap.
2. Adjust MaskTransformation’s getId()’s return.

### CODE REVIEW

**Comment by wasabeef** [comment]
@start141 

Thank you for everything.
May I add you to the `README`?

**Comment by start141** [comment]
HA.
Thanks, if you like!

**Comment by start141** [comment]
I found we can merged `NinePatchMaskTransformation` to the MaskTransformation.
I will pull a new request soon.

**Comment by wasabeef** [comment]
@start141 

I should wait ?

**Comment by start141** [comment]
maybe at noon.

**Comment by wasabeef** [comment]
@start141 

OK. :ship:

**Pull request closed without merging**
