### PR TITLE
Merged NinePatchMaskTransformation to MaskTransformation

### PR DESCRIPTION
**Pull request by start141**
1.merged the NinePatchMaskTransformation to the maskTransformation.
2.replace mask resource.
3.optimize the code.

### CODE REVIEW

**Comment by start141** [comment]
The ScreenCapture:
device-2015-09-18-120241

**Comment by wasabeef** [comment]
@start141 

OK. thanks.

I will merge and release tomorrow.

**Comment by wasabeef** [comment]
@start141 

I just released to 1.2.1

and, i have added you to `README`.
Thanks :shipit:

**Comment by start141** [comment]
Can you merge https://github.com/wasabeef/glide-transformations/pull/22 ?

**Comment by wasabeef** [comment]
yes

**Pull request merged**
